version: "2"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
        - "80:80"
    links:
        - fpm
    volumes:
        - ../:/usr/share/nginx/html/
        - ../nginx.conf:/etc/nginx/http.d/default.conf
    networks:
        - nginx


  fpm:
    image: php
    container_name: fpm
    networks:
        - nginx
    volumes:
        - ../:/usr/share/nginx/html/

networks:
  nginx:
    driver: bridge
